xecore:
        image: hoonmin/xecore:1.8.14
        ports:
                - 80:80
# 파일을 저장할 디렉토리를 지정합니다.
#        volumes:
#                - /xefiles:/var/html/www/files:rw

db:
        image: mariadb
        environment:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: xe
                MYSQL_USER: xe
                MYSQL_PASSWORD: xe
        ports:
                - 3306:3306
# MariaDB의 데이터와 로그를 저장할 디렉토리를 지정합니다.
#        volumes:
#                - /var/lib/mysql:/var/lib/mysql:rw
#                - /var/log/mysql:/var/log/mysql:rw
